package mocks

import mock "github.com/stretchr/testify/mock"

// EventPublisherMock is an autogenerated mock type for the EventPublisher type
type EventPublisherMock struct {
	mock.Mock
}

// Publish provides a mock function with given fields: event, id
func (_m *EventPublisherMock) Publish(event string, id string) error {
	ret := _m.Called(event, id)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(event, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventPublisherMock creates a new instance of EventPublisherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventPublisherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventPublisherMock {
	mock := &EventPublisherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
