package mocks

import (
	context "context"
	models "transfers-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// TransferServiceMock is an autogenerated mock type for the TransfersRepository type
type TransferServiceMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, transfer
func (_m *TransferServiceMock) Create(ctx context.Context, transfer models.Transfer) (string, error) {
	ret := _m.Called(ctx, transfer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Transfer) (string, error)); ok {
		return rf(ctx, transfer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Transfer) string); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Transfer) error); ok {
		r1 = rf(ctx, transfer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TransferServiceMock) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TransferServiceMock) GetByID(ctx context.Context, id string) (models.Transfer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Transfer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Transfer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Transfer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySenderID provides a mock function with given fields: ctx, id
func (_m *TransferServiceMock) GetBySenderID(ctx context.Context, id string) ([]models.Transfer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBySenderID")
	}

	var r0 []models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Transfer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Transfer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, transfer
func (_m *TransferServiceMock) Update(ctx context.Context, transfer models.Transfer) error {
	ret := _m.Called(ctx, transfer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Transfer) error); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransferServiceMock creates a new instance of TransferServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransferServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransferServiceMock {
	mock := &TransferServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
